// Auto-generated by the build process. Do not edit manually.

export interface KnowWhereConfig {
  /** KnowWhere API server base URL */
  endpoint?: string;
  /** KnowWhere API key (if authentication is enabled) */
  apiKey?: string;
  /** Automatically retrieve relevant memories before each prompt */
  autoRecall?: boolean;
  /** Automatically store session transcripts after each agent run */
  autoCapture?: boolean;
  /** Maximum number of memories to retrieve per query */
  topK?: number;
  /** Store session transcript to KnowWhere during context compaction */
  storeOnCompaction?: boolean;
}
